### ISSUE TITLE
Cross posting Bug Report

### ISSUE THREAD

**Issue by bookerthegeek** [gug2/Many-Systems#1]
https://github.com/aidancbrady/Mekanism/issues/4062

Here for your convenience.

**Comment by gug2** [comment]
I'll check in my dev workspace

**Comment by gug2** [comment]
What version of the addon?

**Comment by bookerthegeek** [comment]
> manysystems{9.8.8} [Many Systems] (Addon Many Systems-9.8.8.jar)

**Comment by gug2** [comment]
Fixed in new version
